Allow to resume migration
teespring/lhm pull request #3
Opened 2019-05-03 20:09 UTC by MatiasFernandez

## Problem

We have some really long LHM migrations that we need to run in different phases. That means we need to:

- Start a migration
- Abort it
- Start the migration again but starting at a specific id
- repeat until it's completed

LHM currently doesn't support that

## Solution

Given that this issue is time sensitive (we need to complete a big migration within the next 15 days) I implemented a quick hack to allow us to resume migrations. We can do that running the migration again with an ENV var set specifying at which id to resume the process.

When we set `LHM_RESUME_AT` ENV variable we change the behavior to:
- Skip migrated table creation (because we assume that it exists since a previous aborted run)
- Skip trigger's creation (because we assume that it exists since a previous aborted run)
- Setup Chunker to start copying records since the id specified in `LHM_RESUME_AT`

2019-05-03 20:25 UTC, JavierGelatti approved these changes
Looks good! :+1:

2019-05-03 20:33 UTC, angeles-tellaarena approved these changes
live reviewed with Mati
looks good!

2019-05-06 17:11 UTC, goodgravy requested changes

2019-05-06 17:11 UTC, goodgravy commented on lib/lhm/entangler.rb
> +      return if ENV['LHM_RESUME_AT'].present?
🚫 Why do we not need to kill long-running queries if we're in resume-mode?

2019-05-06 17:11 UTC, goodgravy commented on lib/lhm/migrator.rb
> +      unless ENV['LHM_RESUME_AT'].present?
💭 I have a slight preference for `if` where possible
```suggestion
      if ENV['LHM_RESUME_AT'].blank?
```

2019-05-06 17:11 UTC, goodgravy commented on spec/integration/integration_helper.rb
> +    @connection.select_values(*args)
💭 could refactor other uses of `@connection.select_values(*args)` to use this helper

2019-05-06 17:11 UTC, goodgravy commented on spec/integration/lhm_spec.rb
> +          select_values('SELECT id FROM users').must_equal([5, 6, 7, 8, 9, 10])
💭 this could lead to flaky tests where `AUTO_INCREMENT` isn't initially 1 because some other test runs first.

How about checking the values of `reference` instead?

2019-05-06 17:18 UTC, MatiasFernandez commented on lib/lhm/entangler.rb
> +      return if ENV['LHM_RESUME_AT'].present?
because we don't need to create triggers. they are already there

2019-05-06 17:21 UTC, MatiasFernandez commented on spec/integration/integration_helper.rb
> +    @connection.select_values(*args)
I'm planning on doing a couple of refactors in the implementation of this PR too. I was trying to move forward with this first so we can start running the long migration (We have less than 15 days to complete it or we are screwed) and then clean up the code. So I think I will do it in a separate PR

2019-05-06 17:25 UTC, goodgravy approved these changes

2019-05-06 18:56 UTC, niklasnordlund approved these changes

2019-05-06 20:12 UTC, merged